services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    user: "0"
    ports:
      - "3000:3000"
    volumes:
      - .:/app:z
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    user: "0"
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app:z
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./dev.db
      - PORT=3001
