FROM node:18-alpine

WORKDIR /app


RUN apk add --no-cache openssl build-base python3

COPY package*.json ./
RUN npm install
RUN npm install -g nodemon

COPY . .

RUN npx prisma generate

EXPOSE 3001
CMD ["npm", "run", "dev"]
